### ISSUE TITLE
Any instruction how to try it?

### ISSUE THREAD

**Issue by sergeyklay** [skvadrik/cre2c#2]
Hello,

Is there any  instruction how to install and try cre2c? :)

Thank you

**Comment by skvadrik** [comment]
Hi Sergei!

First of all, let me note that cre2c is my student's attempt to reinvent re2c (http://re2c.org and also https://github.com/skvadrik/re2c). I quickly came to realize that re2c is a better tool and that I would do a better job contributing to re2c directly. So unless you have some particular interest in cre2c, I wholeheartedly recommend that you have a look at re2c instead.

How to build cre2c:
- you will need GHC haskell compiler
- `git clone` the project and go to the top source directory
- simple `make` will build the project: it will call GHC that will compile haskell source files and put the resulting binary in the top source directory
- If you want to regenerate parser files with `happy`, then use `make clean_all && make`

That's all. I've just tested it with GHC-8.0.2 and happy-1.19.5 and it builds fine (with a couple of warnings). Makefile is a quite unusual way of building a haskell project (it should use `ghc --make` and some `cabal` or whatever configuration files instead, but that was long ago).

There's no official way to install it.

If you need any help, let me know.

**Comment by sergeyklay** [comment]
@skvadrik Thank you for quick reply. Should I use Haskell Platform or Stack will be enough?

**Comment by skvadrik** [comment]
I think any GHC would do, either installed with Stack or with Haskell Platform.
Also, I forgot, you'll need `dlist`, `hashable` and `unordered-containers` libraries.

**Comment by sergeyklay** [comment]
I definitely have to try it! Thank you :)
